# Generated by Django 3.2 on 2022-04-03 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("is_archive", models.BooleanField(default=False, verbose_name="Archive")),
                (
                    "members",
                    models.ManyToManyField(related_name="members", to=settings.AUTH_USER_MODEL, verbose_name="Member"),
                ),
                (
                    "owner",
                    models.ManyToManyField(related_name="owner", to=settings.AUTH_USER_MODEL, verbose_name="Owner"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("is_archive", models.BooleanField(default=False, verbose_name="Archive")),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table",
                        to="tables.table",
                        verbose_name="Table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(max_length=1024, verbose_name="Description")),
                ("is_archive", models.BooleanField(default=False, verbose_name="Archive")),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list",
                        to="tables.list",
                        verbose_name="List",
                    ),
                ),
            ],
        ),
    ]
