# Generated by Django 3.2 on 2022-04-16 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tables", "0002_auto_20220414_1021"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="assignee",
        ),
        migrations.AddField(
            model_name="card",
            name="assignee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="assignee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assignee",
            ),
        ),
    ]
